-- ==============================================================
-- Generated by Vitis HLS v2023.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_B : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001011";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln46_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal w8_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w8_ce0 : STD_LOGIC;
    signal w8_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal do_init_reg_321 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal w_index6_reg_336 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_read32_phi_reg_798 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read133_phi_reg_810 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read234_phi_reg_822 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read335_phi_reg_834 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read436_phi_reg_846 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read537_phi_reg_858 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read638_phi_reg_870 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read739_phi_reg_882 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read840_phi_reg_894 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read941_phi_reg_906 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1042_phi_reg_918 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1143_phi_reg_930 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1244_phi_reg_942 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1345_phi_reg_954 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1446_phi_reg_966 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1547_phi_reg_978 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1648_phi_reg_990 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1749_phi_reg_1002 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1850_phi_reg_1014 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1951_phi_reg_1026 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2052_phi_reg_1038 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2153_phi_reg_1050 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2254_phi_reg_1062 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2355_phi_reg_1074 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2456_phi_reg_1086 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2557_phi_reg_1098 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2658_phi_reg_1110 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2759_phi_reg_1122 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2860_phi_reg_1134 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2961_phi_reg_1146 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read3062_phi_reg_1158 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read3163_phi_reg_1170 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_reg_1182 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_do_init_phi_fu_324_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal w_index_fu_1201_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_index_reg_1487 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln46_reg_1492 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_1492_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_1492_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_1213_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_reg_1496 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_reg_1501 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln4_reg_1506 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_fu_1308_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_w_index6_phi_fu_339_p6 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_p_read32_phi_phi_fu_802_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read32_phi_reg_798 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read32_phi_reg_798 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read133_phi_phi_fu_814_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read133_phi_reg_810 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read133_phi_reg_810 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read234_phi_phi_fu_826_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read234_phi_reg_822 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read234_phi_reg_822 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read335_phi_phi_fu_838_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read335_phi_reg_834 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read335_phi_reg_834 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read436_phi_phi_fu_850_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read436_phi_reg_846 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read436_phi_reg_846 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read537_phi_phi_fu_862_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read537_phi_reg_858 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read537_phi_reg_858 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read638_phi_phi_fu_874_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read638_phi_reg_870 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read638_phi_reg_870 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read739_phi_phi_fu_886_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read739_phi_reg_882 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read739_phi_reg_882 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read840_phi_phi_fu_898_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read840_phi_reg_894 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read840_phi_reg_894 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read941_phi_phi_fu_910_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read941_phi_reg_906 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read941_phi_reg_906 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1042_phi_phi_fu_922_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1042_phi_reg_918 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1143_phi_phi_fu_934_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1143_phi_reg_930 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1244_phi_phi_fu_946_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1244_phi_reg_942 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1345_phi_phi_fu_958_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1345_phi_reg_954 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1446_phi_phi_fu_970_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1446_phi_reg_966 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1547_phi_phi_fu_982_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1547_phi_reg_978 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1648_phi_phi_fu_994_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1648_phi_reg_990 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1749_phi_phi_fu_1006_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1749_phi_reg_1002 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1850_phi_phi_fu_1018_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1850_phi_reg_1014 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read1951_phi_phi_fu_1030_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read1951_phi_reg_1026 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2052_phi_phi_fu_1042_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2052_phi_reg_1038 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2153_phi_phi_fu_1054_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2153_phi_reg_1050 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2254_phi_phi_fu_1066_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2254_phi_reg_1062 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2355_phi_phi_fu_1078_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2355_phi_reg_1074 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2456_phi_phi_fu_1090_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2456_phi_reg_1086 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2557_phi_phi_fu_1102_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2557_phi_reg_1098 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2658_phi_phi_fu_1114_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2658_phi_reg_1110 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2759_phi_phi_fu_1126_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2759_phi_reg_1122 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2860_phi_phi_fu_1138_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2860_phi_reg_1134 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read2961_phi_phi_fu_1150_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read2961_phi_reg_1146 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read3062_phi_phi_fu_1162_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read3062_phi_reg_1158 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_read3163_phi_phi_fu_1174_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_read3163_phi_reg_1170 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_phi_fu_1186_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_init_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_init_pp0_iter3_reg : STD_LOGIC;
    signal zext_ln46_fu_1196_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln73_fu_1289_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_fu_1289_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln58_fu_1305_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln46_fu_1314_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal mul_ln73_fu_1289_p10 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_condition_310 : BOOLEAN;
    signal ap_condition_331 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mux_32_5_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (7 downto 0);
        din17 : IN STD_LOGIC_VECTOR (7 downto 0);
        din18 : IN STD_LOGIC_VECTOR (7 downto 0);
        din19 : IN STD_LOGIC_VECTOR (7 downto 0);
        din20 : IN STD_LOGIC_VECTOR (7 downto 0);
        din21 : IN STD_LOGIC_VECTOR (7 downto 0);
        din22 : IN STD_LOGIC_VECTOR (7 downto 0);
        din23 : IN STD_LOGIC_VECTOR (7 downto 0);
        din24 : IN STD_LOGIC_VECTOR (7 downto 0);
        din25 : IN STD_LOGIC_VECTOR (7 downto 0);
        din26 : IN STD_LOGIC_VECTOR (7 downto 0);
        din27 : IN STD_LOGIC_VECTOR (7 downto 0);
        din28 : IN STD_LOGIC_VECTOR (7 downto 0);
        din29 : IN STD_LOGIC_VECTOR (7 downto 0);
        din30 : IN STD_LOGIC_VECTOR (7 downto 0);
        din31 : IN STD_LOGIC_VECTOR (7 downto 0);
        din32 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component myproject_mul_11s_8ns_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s_w8_ROM_NP_dEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    w8_U : component myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s_w8_ROM_NP_dEe
    generic map (
        DataWidth => 11,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w8_address0,
        ce0 => w8_ce0,
        q0 => w8_q0);

    mux_32_5_8_1_1_U395 : component myproject_mux_32_5_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 5,
        dout_WIDTH => 8)
    port map (
        din0 => ap_phi_mux_p_read32_phi_phi_fu_802_p4,
        din1 => ap_phi_mux_p_read133_phi_phi_fu_814_p4,
        din2 => ap_phi_mux_p_read234_phi_phi_fu_826_p4,
        din3 => ap_phi_mux_p_read335_phi_phi_fu_838_p4,
        din4 => ap_phi_mux_p_read436_phi_phi_fu_850_p4,
        din5 => ap_phi_mux_p_read537_phi_phi_fu_862_p4,
        din6 => ap_phi_mux_p_read638_phi_phi_fu_874_p4,
        din7 => ap_phi_mux_p_read739_phi_phi_fu_886_p4,
        din8 => ap_phi_mux_p_read840_phi_phi_fu_898_p4,
        din9 => ap_phi_mux_p_read941_phi_phi_fu_910_p4,
        din10 => ap_phi_mux_p_read1042_phi_phi_fu_922_p4,
        din11 => ap_phi_mux_p_read1143_phi_phi_fu_934_p4,
        din12 => ap_phi_mux_p_read1244_phi_phi_fu_946_p4,
        din13 => ap_phi_mux_p_read1345_phi_phi_fu_958_p4,
        din14 => ap_phi_mux_p_read1446_phi_phi_fu_970_p4,
        din15 => ap_phi_mux_p_read1547_phi_phi_fu_982_p4,
        din16 => ap_phi_mux_p_read1648_phi_phi_fu_994_p4,
        din17 => ap_phi_mux_p_read1749_phi_phi_fu_1006_p4,
        din18 => ap_phi_mux_p_read1850_phi_phi_fu_1018_p4,
        din19 => ap_phi_mux_p_read1951_phi_phi_fu_1030_p4,
        din20 => ap_phi_mux_p_read2052_phi_phi_fu_1042_p4,
        din21 => ap_phi_mux_p_read2153_phi_phi_fu_1054_p4,
        din22 => ap_phi_mux_p_read2254_phi_phi_fu_1066_p4,
        din23 => ap_phi_mux_p_read2355_phi_phi_fu_1078_p4,
        din24 => ap_phi_mux_p_read2456_phi_phi_fu_1090_p4,
        din25 => ap_phi_mux_p_read2557_phi_phi_fu_1102_p4,
        din26 => ap_phi_mux_p_read2658_phi_phi_fu_1114_p4,
        din27 => ap_phi_mux_p_read2759_phi_phi_fu_1126_p4,
        din28 => ap_phi_mux_p_read2860_phi_phi_fu_1138_p4,
        din29 => ap_phi_mux_p_read2961_phi_phi_fu_1150_p4,
        din30 => ap_phi_mux_p_read3062_phi_phi_fu_1162_p4,
        din31 => ap_phi_mux_p_read3163_phi_phi_fu_1174_p4,
        din32 => w_index6_reg_336,
        dout => a_fu_1213_p34);

    mul_11s_8ns_19_1_1_U396 : component myproject_mul_11s_8ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 8,
        dout_WIDTH => 19)
    port map (
        din0 => w_reg_1501,
        din1 => mul_ln73_fu_1289_p1,
        dout => mul_ln73_fu_1289_p2);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv12_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln46_reg_1492_pp0_iter2_reg = ap_const_lv1_1))) then 
                    ap_return_preg <= trunc_ln46_fu_1314_p1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918 <= p_read10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918 <= ap_phi_reg_pp0_iter0_p_read1042_phi_reg_918;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930 <= p_read11;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930 <= ap_phi_reg_pp0_iter0_p_read1143_phi_reg_930;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942 <= p_read12;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942 <= ap_phi_reg_pp0_iter0_p_read1244_phi_reg_942;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read133_phi_reg_810_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read133_phi_reg_810 <= p_read1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read133_phi_reg_810 <= ap_phi_reg_pp0_iter0_p_read133_phi_reg_810;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954 <= p_read13;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954 <= ap_phi_reg_pp0_iter0_p_read1345_phi_reg_954;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966 <= p_read14;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966 <= ap_phi_reg_pp0_iter0_p_read1446_phi_reg_966;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978 <= p_read15;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978 <= ap_phi_reg_pp0_iter0_p_read1547_phi_reg_978;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990 <= p_read16;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990 <= ap_phi_reg_pp0_iter0_p_read1648_phi_reg_990;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002 <= p_read17;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002 <= ap_phi_reg_pp0_iter0_p_read1749_phi_reg_1002;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014 <= p_read18;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014 <= ap_phi_reg_pp0_iter0_p_read1850_phi_reg_1014;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026 <= p_read19;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026 <= ap_phi_reg_pp0_iter0_p_read1951_phi_reg_1026;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038 <= p_read20;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038 <= ap_phi_reg_pp0_iter0_p_read2052_phi_reg_1038;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050 <= p_read21;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050 <= ap_phi_reg_pp0_iter0_p_read2153_phi_reg_1050;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062 <= p_read22;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062 <= ap_phi_reg_pp0_iter0_p_read2254_phi_reg_1062;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read234_phi_reg_822_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read234_phi_reg_822 <= p_read2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read234_phi_reg_822 <= ap_phi_reg_pp0_iter0_p_read234_phi_reg_822;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074 <= p_read23;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074 <= ap_phi_reg_pp0_iter0_p_read2355_phi_reg_1074;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086 <= p_read24;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086 <= ap_phi_reg_pp0_iter0_p_read2456_phi_reg_1086;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098 <= p_read25;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098 <= ap_phi_reg_pp0_iter0_p_read2557_phi_reg_1098;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110 <= p_read26;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110 <= ap_phi_reg_pp0_iter0_p_read2658_phi_reg_1110;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122 <= p_read27;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122 <= ap_phi_reg_pp0_iter0_p_read2759_phi_reg_1122;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134 <= p_read28;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134 <= ap_phi_reg_pp0_iter0_p_read2860_phi_reg_1134;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146 <= p_read29;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146 <= ap_phi_reg_pp0_iter0_p_read2961_phi_reg_1146;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158 <= p_read30;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158 <= ap_phi_reg_pp0_iter0_p_read3062_phi_reg_1158;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170 <= p_read31;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170 <= ap_phi_reg_pp0_iter0_p_read3163_phi_reg_1170;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read32_phi_reg_798_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read32_phi_reg_798 <= p_read;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read32_phi_reg_798 <= ap_phi_reg_pp0_iter0_p_read32_phi_reg_798;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read335_phi_reg_834_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read335_phi_reg_834 <= p_read3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read335_phi_reg_834 <= ap_phi_reg_pp0_iter0_p_read335_phi_reg_834;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read436_phi_reg_846_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read436_phi_reg_846 <= p_read4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read436_phi_reg_846 <= ap_phi_reg_pp0_iter0_p_read436_phi_reg_846;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read537_phi_reg_858_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read537_phi_reg_858 <= p_read5;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read537_phi_reg_858 <= ap_phi_reg_pp0_iter0_p_read537_phi_reg_858;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read638_phi_reg_870_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read638_phi_reg_870 <= p_read6;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read638_phi_reg_870 <= ap_phi_reg_pp0_iter0_p_read638_phi_reg_870;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read739_phi_reg_882_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read739_phi_reg_882 <= p_read7;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read739_phi_reg_882 <= ap_phi_reg_pp0_iter0_p_read739_phi_reg_882;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read840_phi_reg_894_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read840_phi_reg_894 <= p_read8;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read840_phi_reg_894 <= ap_phi_reg_pp0_iter0_p_read840_phi_reg_894;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_read941_phi_reg_906_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if ((ap_phi_mux_do_init_phi_fu_324_p6 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_p_read941_phi_reg_906 <= p_read9;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_read941_phi_reg_906 <= ap_phi_reg_pp0_iter0_p_read941_phi_reg_906;
                end if;
            end if; 
        end if;
    end process;

    do_init_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln46_reg_1492 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                do_init_reg_321 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln46_reg_1492 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                do_init_reg_321 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    empty_reg_1182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if ((icmp_ln46_reg_1492_pp0_iter2_reg = ap_const_lv1_1)) then 
                    empty_reg_1182 <= ap_const_lv16_B;
                elsif ((icmp_ln46_reg_1492_pp0_iter2_reg = ap_const_lv1_0)) then 
                    empty_reg_1182 <= add_ln58_fu_1308_p2;
                end if;
            end if; 
        end if;
    end process;

    p_read1042_phi_reg_918_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1042_phi_reg_918 <= p_read1042_phi_reg_918;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1042_phi_reg_918 <= ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918;
                end if;
            end if; 
        end if;
    end process;

    p_read1143_phi_reg_930_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1143_phi_reg_930 <= p_read1143_phi_reg_930;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1143_phi_reg_930 <= ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930;
                end if;
            end if; 
        end if;
    end process;

    p_read1244_phi_reg_942_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1244_phi_reg_942 <= p_read1244_phi_reg_942;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1244_phi_reg_942 <= ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942;
                end if;
            end if; 
        end if;
    end process;

    p_read133_phi_reg_810_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read133_phi_reg_810 <= p_read133_phi_reg_810;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read133_phi_reg_810 <= ap_phi_reg_pp0_iter1_p_read133_phi_reg_810;
                end if;
            end if; 
        end if;
    end process;

    p_read1345_phi_reg_954_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1345_phi_reg_954 <= p_read1345_phi_reg_954;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1345_phi_reg_954 <= ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954;
                end if;
            end if; 
        end if;
    end process;

    p_read1446_phi_reg_966_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1446_phi_reg_966 <= p_read1446_phi_reg_966;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1446_phi_reg_966 <= ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966;
                end if;
            end if; 
        end if;
    end process;

    p_read1547_phi_reg_978_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1547_phi_reg_978 <= p_read1547_phi_reg_978;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1547_phi_reg_978 <= ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978;
                end if;
            end if; 
        end if;
    end process;

    p_read1648_phi_reg_990_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1648_phi_reg_990 <= p_read1648_phi_reg_990;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1648_phi_reg_990 <= ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990;
                end if;
            end if; 
        end if;
    end process;

    p_read1749_phi_reg_1002_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1749_phi_reg_1002 <= p_read1749_phi_reg_1002;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1749_phi_reg_1002 <= ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002;
                end if;
            end if; 
        end if;
    end process;

    p_read1850_phi_reg_1014_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1850_phi_reg_1014 <= p_read1850_phi_reg_1014;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1850_phi_reg_1014 <= ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014;
                end if;
            end if; 
        end if;
    end process;

    p_read1951_phi_reg_1026_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read1951_phi_reg_1026 <= p_read1951_phi_reg_1026;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read1951_phi_reg_1026 <= ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026;
                end if;
            end if; 
        end if;
    end process;

    p_read2052_phi_reg_1038_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2052_phi_reg_1038 <= p_read2052_phi_reg_1038;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2052_phi_reg_1038 <= ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038;
                end if;
            end if; 
        end if;
    end process;

    p_read2153_phi_reg_1050_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2153_phi_reg_1050 <= p_read2153_phi_reg_1050;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2153_phi_reg_1050 <= ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050;
                end if;
            end if; 
        end if;
    end process;

    p_read2254_phi_reg_1062_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2254_phi_reg_1062 <= p_read2254_phi_reg_1062;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2254_phi_reg_1062 <= ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062;
                end if;
            end if; 
        end if;
    end process;

    p_read234_phi_reg_822_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read234_phi_reg_822 <= p_read234_phi_reg_822;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read234_phi_reg_822 <= ap_phi_reg_pp0_iter1_p_read234_phi_reg_822;
                end if;
            end if; 
        end if;
    end process;

    p_read2355_phi_reg_1074_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2355_phi_reg_1074 <= p_read2355_phi_reg_1074;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2355_phi_reg_1074 <= ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074;
                end if;
            end if; 
        end if;
    end process;

    p_read2456_phi_reg_1086_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2456_phi_reg_1086 <= p_read2456_phi_reg_1086;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2456_phi_reg_1086 <= ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086;
                end if;
            end if; 
        end if;
    end process;

    p_read2557_phi_reg_1098_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2557_phi_reg_1098 <= p_read2557_phi_reg_1098;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2557_phi_reg_1098 <= ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098;
                end if;
            end if; 
        end if;
    end process;

    p_read2658_phi_reg_1110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2658_phi_reg_1110 <= p_read2658_phi_reg_1110;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2658_phi_reg_1110 <= ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110;
                end if;
            end if; 
        end if;
    end process;

    p_read2759_phi_reg_1122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2759_phi_reg_1122 <= p_read2759_phi_reg_1122;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2759_phi_reg_1122 <= ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122;
                end if;
            end if; 
        end if;
    end process;

    p_read2860_phi_reg_1134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2860_phi_reg_1134 <= p_read2860_phi_reg_1134;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2860_phi_reg_1134 <= ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134;
                end if;
            end if; 
        end if;
    end process;

    p_read2961_phi_reg_1146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read2961_phi_reg_1146 <= p_read2961_phi_reg_1146;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read2961_phi_reg_1146 <= ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146;
                end if;
            end if; 
        end if;
    end process;

    p_read3062_phi_reg_1158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read3062_phi_reg_1158 <= p_read3062_phi_reg_1158;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read3062_phi_reg_1158 <= ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158;
                end if;
            end if; 
        end if;
    end process;

    p_read3163_phi_reg_1170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read3163_phi_reg_1170 <= p_read3163_phi_reg_1170;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read3163_phi_reg_1170 <= ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170;
                end if;
            end if; 
        end if;
    end process;

    p_read32_phi_reg_798_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read32_phi_reg_798 <= p_read32_phi_reg_798;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read32_phi_reg_798 <= ap_phi_reg_pp0_iter1_p_read32_phi_reg_798;
                end if;
            end if; 
        end if;
    end process;

    p_read335_phi_reg_834_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read335_phi_reg_834 <= p_read335_phi_reg_834;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read335_phi_reg_834 <= ap_phi_reg_pp0_iter1_p_read335_phi_reg_834;
                end if;
            end if; 
        end if;
    end process;

    p_read436_phi_reg_846_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read436_phi_reg_846 <= p_read436_phi_reg_846;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read436_phi_reg_846 <= ap_phi_reg_pp0_iter1_p_read436_phi_reg_846;
                end if;
            end if; 
        end if;
    end process;

    p_read537_phi_reg_858_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read537_phi_reg_858 <= p_read537_phi_reg_858;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read537_phi_reg_858 <= ap_phi_reg_pp0_iter1_p_read537_phi_reg_858;
                end if;
            end if; 
        end if;
    end process;

    p_read638_phi_reg_870_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read638_phi_reg_870 <= p_read638_phi_reg_870;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read638_phi_reg_870 <= ap_phi_reg_pp0_iter1_p_read638_phi_reg_870;
                end if;
            end if; 
        end if;
    end process;

    p_read739_phi_reg_882_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read739_phi_reg_882 <= p_read739_phi_reg_882;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read739_phi_reg_882 <= ap_phi_reg_pp0_iter1_p_read739_phi_reg_882;
                end if;
            end if; 
        end if;
    end process;

    p_read840_phi_reg_894_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read840_phi_reg_894 <= p_read840_phi_reg_894;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read840_phi_reg_894 <= ap_phi_reg_pp0_iter1_p_read840_phi_reg_894;
                end if;
            end if; 
        end if;
    end process;

    p_read941_phi_reg_906_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_331)) then
                if ((do_init_reg_321 = ap_const_lv1_0)) then 
                    p_read941_phi_reg_906 <= p_read941_phi_reg_906;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_read941_phi_reg_906 <= ap_phi_reg_pp0_iter1_p_read941_phi_reg_906;
                end if;
            end if; 
        end if;
    end process;

    w_index6_reg_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln46_reg_1492 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                w_index6_reg_336 <= w_index_reg_1487;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln46_reg_1492 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                w_index6_reg_336 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_reg_1496 <= a_fu_1213_p34;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_init_pp0_iter1_reg <= ap_loop_init;
                ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
                icmp_ln46_reg_1492 <= icmp_ln46_fu_1207_p2;
                icmp_ln46_reg_1492_pp0_iter1_reg <= icmp_ln46_reg_1492;
                w_reg_1501 <= w8_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
                icmp_ln46_reg_1492_pp0_iter2_reg <= icmp_ln46_reg_1492_pp0_iter1_reg;
                trunc_ln4_reg_1506 <= mul_ln73_fu_1289_p2(18 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                w_index_reg_1487 <= w_index_fu_1201_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_fu_1308_p2 <= std_logic_vector(signed(sext_ln58_fu_1305_p1) + signed(ap_phi_mux_empty_phi_fu_1186_p6));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_310_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_310 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_331_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_331 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln46_fu_1207_p2, ap_start_int)
    begin
        if (((icmp_ln46_fu_1207_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_do_init_phi_fu_324_p6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, do_init_reg_321, icmp_ln46_reg_1492, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln46_reg_1492 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_do_init_phi_fu_324_p6 <= ap_const_lv1_0;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln46_reg_1492 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ap_phi_mux_do_init_phi_fu_324_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_do_init_phi_fu_324_p6 <= do_init_reg_321;
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_1186_p6_assign_proc : process(empty_reg_1182, ap_loop_init_pp0_iter3_reg)
    begin
        if ((ap_loop_init_pp0_iter3_reg = ap_const_logic_1)) then 
            ap_phi_mux_empty_phi_fu_1186_p6 <= ap_const_lv16_B;
        else 
            ap_phi_mux_empty_phi_fu_1186_p6 <= empty_reg_1182;
        end if; 
    end process;


    ap_phi_mux_p_read1042_phi_phi_fu_922_p4_assign_proc : process(do_init_reg_321, p_read1042_phi_reg_918, ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1042_phi_phi_fu_922_p4 <= p_read1042_phi_reg_918;
        else 
            ap_phi_mux_p_read1042_phi_phi_fu_922_p4 <= ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918;
        end if; 
    end process;


    ap_phi_mux_p_read1143_phi_phi_fu_934_p4_assign_proc : process(do_init_reg_321, p_read1143_phi_reg_930, ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1143_phi_phi_fu_934_p4 <= p_read1143_phi_reg_930;
        else 
            ap_phi_mux_p_read1143_phi_phi_fu_934_p4 <= ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930;
        end if; 
    end process;


    ap_phi_mux_p_read1244_phi_phi_fu_946_p4_assign_proc : process(do_init_reg_321, p_read1244_phi_reg_942, ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1244_phi_phi_fu_946_p4 <= p_read1244_phi_reg_942;
        else 
            ap_phi_mux_p_read1244_phi_phi_fu_946_p4 <= ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942;
        end if; 
    end process;


    ap_phi_mux_p_read133_phi_phi_fu_814_p4_assign_proc : process(do_init_reg_321, p_read133_phi_reg_810, ap_phi_reg_pp0_iter1_p_read133_phi_reg_810)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read133_phi_phi_fu_814_p4 <= p_read133_phi_reg_810;
        else 
            ap_phi_mux_p_read133_phi_phi_fu_814_p4 <= ap_phi_reg_pp0_iter1_p_read133_phi_reg_810;
        end if; 
    end process;


    ap_phi_mux_p_read1345_phi_phi_fu_958_p4_assign_proc : process(do_init_reg_321, p_read1345_phi_reg_954, ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1345_phi_phi_fu_958_p4 <= p_read1345_phi_reg_954;
        else 
            ap_phi_mux_p_read1345_phi_phi_fu_958_p4 <= ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954;
        end if; 
    end process;


    ap_phi_mux_p_read1446_phi_phi_fu_970_p4_assign_proc : process(do_init_reg_321, p_read1446_phi_reg_966, ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1446_phi_phi_fu_970_p4 <= p_read1446_phi_reg_966;
        else 
            ap_phi_mux_p_read1446_phi_phi_fu_970_p4 <= ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966;
        end if; 
    end process;


    ap_phi_mux_p_read1547_phi_phi_fu_982_p4_assign_proc : process(do_init_reg_321, p_read1547_phi_reg_978, ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1547_phi_phi_fu_982_p4 <= p_read1547_phi_reg_978;
        else 
            ap_phi_mux_p_read1547_phi_phi_fu_982_p4 <= ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978;
        end if; 
    end process;


    ap_phi_mux_p_read1648_phi_phi_fu_994_p4_assign_proc : process(do_init_reg_321, p_read1648_phi_reg_990, ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1648_phi_phi_fu_994_p4 <= p_read1648_phi_reg_990;
        else 
            ap_phi_mux_p_read1648_phi_phi_fu_994_p4 <= ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990;
        end if; 
    end process;


    ap_phi_mux_p_read1749_phi_phi_fu_1006_p4_assign_proc : process(do_init_reg_321, p_read1749_phi_reg_1002, ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1749_phi_phi_fu_1006_p4 <= p_read1749_phi_reg_1002;
        else 
            ap_phi_mux_p_read1749_phi_phi_fu_1006_p4 <= ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002;
        end if; 
    end process;


    ap_phi_mux_p_read1850_phi_phi_fu_1018_p4_assign_proc : process(do_init_reg_321, p_read1850_phi_reg_1014, ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1850_phi_phi_fu_1018_p4 <= p_read1850_phi_reg_1014;
        else 
            ap_phi_mux_p_read1850_phi_phi_fu_1018_p4 <= ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014;
        end if; 
    end process;


    ap_phi_mux_p_read1951_phi_phi_fu_1030_p4_assign_proc : process(do_init_reg_321, p_read1951_phi_reg_1026, ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read1951_phi_phi_fu_1030_p4 <= p_read1951_phi_reg_1026;
        else 
            ap_phi_mux_p_read1951_phi_phi_fu_1030_p4 <= ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026;
        end if; 
    end process;


    ap_phi_mux_p_read2052_phi_phi_fu_1042_p4_assign_proc : process(do_init_reg_321, p_read2052_phi_reg_1038, ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2052_phi_phi_fu_1042_p4 <= p_read2052_phi_reg_1038;
        else 
            ap_phi_mux_p_read2052_phi_phi_fu_1042_p4 <= ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038;
        end if; 
    end process;


    ap_phi_mux_p_read2153_phi_phi_fu_1054_p4_assign_proc : process(do_init_reg_321, p_read2153_phi_reg_1050, ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2153_phi_phi_fu_1054_p4 <= p_read2153_phi_reg_1050;
        else 
            ap_phi_mux_p_read2153_phi_phi_fu_1054_p4 <= ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050;
        end if; 
    end process;


    ap_phi_mux_p_read2254_phi_phi_fu_1066_p4_assign_proc : process(do_init_reg_321, p_read2254_phi_reg_1062, ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2254_phi_phi_fu_1066_p4 <= p_read2254_phi_reg_1062;
        else 
            ap_phi_mux_p_read2254_phi_phi_fu_1066_p4 <= ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062;
        end if; 
    end process;


    ap_phi_mux_p_read234_phi_phi_fu_826_p4_assign_proc : process(do_init_reg_321, p_read234_phi_reg_822, ap_phi_reg_pp0_iter1_p_read234_phi_reg_822)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read234_phi_phi_fu_826_p4 <= p_read234_phi_reg_822;
        else 
            ap_phi_mux_p_read234_phi_phi_fu_826_p4 <= ap_phi_reg_pp0_iter1_p_read234_phi_reg_822;
        end if; 
    end process;


    ap_phi_mux_p_read2355_phi_phi_fu_1078_p4_assign_proc : process(do_init_reg_321, p_read2355_phi_reg_1074, ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2355_phi_phi_fu_1078_p4 <= p_read2355_phi_reg_1074;
        else 
            ap_phi_mux_p_read2355_phi_phi_fu_1078_p4 <= ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074;
        end if; 
    end process;


    ap_phi_mux_p_read2456_phi_phi_fu_1090_p4_assign_proc : process(do_init_reg_321, p_read2456_phi_reg_1086, ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2456_phi_phi_fu_1090_p4 <= p_read2456_phi_reg_1086;
        else 
            ap_phi_mux_p_read2456_phi_phi_fu_1090_p4 <= ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086;
        end if; 
    end process;


    ap_phi_mux_p_read2557_phi_phi_fu_1102_p4_assign_proc : process(do_init_reg_321, p_read2557_phi_reg_1098, ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2557_phi_phi_fu_1102_p4 <= p_read2557_phi_reg_1098;
        else 
            ap_phi_mux_p_read2557_phi_phi_fu_1102_p4 <= ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098;
        end if; 
    end process;


    ap_phi_mux_p_read2658_phi_phi_fu_1114_p4_assign_proc : process(do_init_reg_321, p_read2658_phi_reg_1110, ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2658_phi_phi_fu_1114_p4 <= p_read2658_phi_reg_1110;
        else 
            ap_phi_mux_p_read2658_phi_phi_fu_1114_p4 <= ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110;
        end if; 
    end process;


    ap_phi_mux_p_read2759_phi_phi_fu_1126_p4_assign_proc : process(do_init_reg_321, p_read2759_phi_reg_1122, ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2759_phi_phi_fu_1126_p4 <= p_read2759_phi_reg_1122;
        else 
            ap_phi_mux_p_read2759_phi_phi_fu_1126_p4 <= ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122;
        end if; 
    end process;


    ap_phi_mux_p_read2860_phi_phi_fu_1138_p4_assign_proc : process(do_init_reg_321, p_read2860_phi_reg_1134, ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2860_phi_phi_fu_1138_p4 <= p_read2860_phi_reg_1134;
        else 
            ap_phi_mux_p_read2860_phi_phi_fu_1138_p4 <= ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134;
        end if; 
    end process;


    ap_phi_mux_p_read2961_phi_phi_fu_1150_p4_assign_proc : process(do_init_reg_321, p_read2961_phi_reg_1146, ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read2961_phi_phi_fu_1150_p4 <= p_read2961_phi_reg_1146;
        else 
            ap_phi_mux_p_read2961_phi_phi_fu_1150_p4 <= ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146;
        end if; 
    end process;


    ap_phi_mux_p_read3062_phi_phi_fu_1162_p4_assign_proc : process(do_init_reg_321, p_read3062_phi_reg_1158, ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read3062_phi_phi_fu_1162_p4 <= p_read3062_phi_reg_1158;
        else 
            ap_phi_mux_p_read3062_phi_phi_fu_1162_p4 <= ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158;
        end if; 
    end process;


    ap_phi_mux_p_read3163_phi_phi_fu_1174_p4_assign_proc : process(do_init_reg_321, p_read3163_phi_reg_1170, ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read3163_phi_phi_fu_1174_p4 <= p_read3163_phi_reg_1170;
        else 
            ap_phi_mux_p_read3163_phi_phi_fu_1174_p4 <= ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170;
        end if; 
    end process;


    ap_phi_mux_p_read32_phi_phi_fu_802_p4_assign_proc : process(do_init_reg_321, p_read32_phi_reg_798, ap_phi_reg_pp0_iter1_p_read32_phi_reg_798)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read32_phi_phi_fu_802_p4 <= p_read32_phi_reg_798;
        else 
            ap_phi_mux_p_read32_phi_phi_fu_802_p4 <= ap_phi_reg_pp0_iter1_p_read32_phi_reg_798;
        end if; 
    end process;


    ap_phi_mux_p_read335_phi_phi_fu_838_p4_assign_proc : process(do_init_reg_321, p_read335_phi_reg_834, ap_phi_reg_pp0_iter1_p_read335_phi_reg_834)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read335_phi_phi_fu_838_p4 <= p_read335_phi_reg_834;
        else 
            ap_phi_mux_p_read335_phi_phi_fu_838_p4 <= ap_phi_reg_pp0_iter1_p_read335_phi_reg_834;
        end if; 
    end process;


    ap_phi_mux_p_read436_phi_phi_fu_850_p4_assign_proc : process(do_init_reg_321, p_read436_phi_reg_846, ap_phi_reg_pp0_iter1_p_read436_phi_reg_846)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read436_phi_phi_fu_850_p4 <= p_read436_phi_reg_846;
        else 
            ap_phi_mux_p_read436_phi_phi_fu_850_p4 <= ap_phi_reg_pp0_iter1_p_read436_phi_reg_846;
        end if; 
    end process;


    ap_phi_mux_p_read537_phi_phi_fu_862_p4_assign_proc : process(do_init_reg_321, p_read537_phi_reg_858, ap_phi_reg_pp0_iter1_p_read537_phi_reg_858)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read537_phi_phi_fu_862_p4 <= p_read537_phi_reg_858;
        else 
            ap_phi_mux_p_read537_phi_phi_fu_862_p4 <= ap_phi_reg_pp0_iter1_p_read537_phi_reg_858;
        end if; 
    end process;


    ap_phi_mux_p_read638_phi_phi_fu_874_p4_assign_proc : process(do_init_reg_321, p_read638_phi_reg_870, ap_phi_reg_pp0_iter1_p_read638_phi_reg_870)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read638_phi_phi_fu_874_p4 <= p_read638_phi_reg_870;
        else 
            ap_phi_mux_p_read638_phi_phi_fu_874_p4 <= ap_phi_reg_pp0_iter1_p_read638_phi_reg_870;
        end if; 
    end process;


    ap_phi_mux_p_read739_phi_phi_fu_886_p4_assign_proc : process(do_init_reg_321, p_read739_phi_reg_882, ap_phi_reg_pp0_iter1_p_read739_phi_reg_882)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read739_phi_phi_fu_886_p4 <= p_read739_phi_reg_882;
        else 
            ap_phi_mux_p_read739_phi_phi_fu_886_p4 <= ap_phi_reg_pp0_iter1_p_read739_phi_reg_882;
        end if; 
    end process;


    ap_phi_mux_p_read840_phi_phi_fu_898_p4_assign_proc : process(do_init_reg_321, p_read840_phi_reg_894, ap_phi_reg_pp0_iter1_p_read840_phi_reg_894)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read840_phi_phi_fu_898_p4 <= p_read840_phi_reg_894;
        else 
            ap_phi_mux_p_read840_phi_phi_fu_898_p4 <= ap_phi_reg_pp0_iter1_p_read840_phi_reg_894;
        end if; 
    end process;


    ap_phi_mux_p_read941_phi_phi_fu_910_p4_assign_proc : process(do_init_reg_321, p_read941_phi_reg_906, ap_phi_reg_pp0_iter1_p_read941_phi_reg_906)
    begin
        if ((do_init_reg_321 = ap_const_lv1_0)) then 
            ap_phi_mux_p_read941_phi_phi_fu_910_p4 <= p_read941_phi_reg_906;
        else 
            ap_phi_mux_p_read941_phi_phi_fu_910_p4 <= ap_phi_reg_pp0_iter1_p_read941_phi_reg_906;
        end if; 
    end process;


    ap_phi_mux_w_index6_phi_fu_339_p6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, w_index6_reg_336, w_index_reg_1487, icmp_ln46_reg_1492, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln46_reg_1492 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_w_index6_phi_fu_339_p6 <= w_index_reg_1487;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln46_reg_1492 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ap_phi_mux_w_index6_phi_fu_339_p6 <= ap_const_lv5_0;
        else 
            ap_phi_mux_w_index6_phi_fu_339_p6 <= w_index6_reg_336;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_p_read1042_phi_reg_918 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1143_phi_reg_930 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1244_phi_reg_942 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read133_phi_reg_810 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1345_phi_reg_954 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1446_phi_reg_966 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1547_phi_reg_978 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1648_phi_reg_990 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1749_phi_reg_1002 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1850_phi_reg_1014 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read1951_phi_reg_1026 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2052_phi_reg_1038 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2153_phi_reg_1050 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2254_phi_reg_1062 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read234_phi_reg_822 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2355_phi_reg_1074 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2456_phi_reg_1086 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2557_phi_reg_1098 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2658_phi_reg_1110 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2759_phi_reg_1122 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2860_phi_reg_1134 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read2961_phi_reg_1146 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read3062_phi_reg_1158 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read3163_phi_reg_1170 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read32_phi_reg_798 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read335_phi_reg_834 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read436_phi_reg_846 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read537_phi_reg_858 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read638_phi_reg_870 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read739_phi_reg_882 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read840_phi_reg_894 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_read941_phi_reg_906 <= "XXXXXXXX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_idle_pp0_0to2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_0to2 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln46_reg_1492_pp0_iter2_reg, trunc_ln46_fu_1314_p1, ap_return_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln46_reg_1492_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_return <= trunc_ln46_fu_1314_p1;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    icmp_ln46_fu_1207_p2 <= "1" when (ap_phi_mux_w_index6_phi_fu_339_p6 = ap_const_lv5_1F) else "0";
    mul_ln73_fu_1289_p1 <= mul_ln73_fu_1289_p10(8 - 1 downto 0);
    mul_ln73_fu_1289_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_reg_1496),19));
        sext_ln58_fu_1305_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln4_reg_1506),16));

    trunc_ln46_fu_1314_p1 <= add_ln58_fu_1308_p2(12 - 1 downto 0);
    w8_address0 <= zext_ln46_fu_1196_p1(5 - 1 downto 0);

    w8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w8_ce0 <= ap_const_logic_1;
        else 
            w8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_index_fu_1201_p2 <= std_logic_vector(unsigned(ap_phi_mux_w_index6_phi_fu_339_p6) + unsigned(ap_const_lv5_1));
    zext_ln46_fu_1196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_w_index6_phi_fu_339_p6),64));
end behav;
