// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_ap_fixed_16_10_5_3_0_ap_fixed_16_6_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [14:0] p_read;
input  [14:0] p_read1;
input  [14:0] p_read2;
input  [14:0] p_read3;
input  [14:0] p_read4;
input  [14:0] p_read5;
input  [14:0] p_read6;
input  [14:0] p_read7;
input  [14:0] p_read8;
input  [14:0] p_read9;
input  [14:0] p_read10;
input  [14:0] p_read11;
input  [14:0] p_read12;
input  [14:0] p_read13;
input  [14:0] p_read14;
input  [14:0] p_read15;
input  [14:0] p_read16;
input  [14:0] p_read17;
input  [14:0] p_read18;
input  [14:0] p_read19;
input  [14:0] p_read20;
input  [14:0] p_read21;
input  [14:0] p_read22;
input  [14:0] p_read23;
input  [14:0] p_read24;
input  [14:0] p_read25;
input  [14:0] p_read26;
input  [14:0] p_read27;
input  [14:0] p_read28;
input  [14:0] p_read29;
input  [14:0] p_read30;
input  [14:0] p_read31;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;
reg[15:0] ap_return_12;
reg[15:0] ap_return_13;
reg[15:0] ap_return_14;
reg[15:0] ap_return_15;
reg[15:0] ap_return_16;
reg[15:0] ap_return_17;
reg[15:0] ap_return_18;
reg[15:0] ap_return_19;
reg[15:0] ap_return_20;
reg[15:0] ap_return_21;
reg[15:0] ap_return_22;
reg[15:0] ap_return_23;
reg[15:0] ap_return_24;
reg[15:0] ap_return_25;
reg[15:0] ap_return_26;
reg[15:0] ap_return_27;
reg[15:0] ap_return_28;
reg[15:0] ap_return_29;
reg[15:0] ap_return_30;
reg[15:0] ap_return_31;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [25:0] y_fu_306_p3;
wire   [25:0] add_ln54_fu_314_p2;
wire   [25:0] y_1_fu_330_p3;
wire   [25:0] add_ln54_1_fu_338_p2;
wire   [25:0] y_2_fu_354_p3;
wire   [25:0] add_ln54_2_fu_362_p2;
wire   [25:0] y_3_fu_378_p3;
wire   [25:0] add_ln54_3_fu_386_p2;
wire   [25:0] y_4_fu_402_p3;
wire   [25:0] add_ln54_4_fu_410_p2;
wire   [25:0] y_5_fu_426_p3;
wire   [25:0] add_ln54_5_fu_434_p2;
wire   [25:0] y_6_fu_450_p3;
wire   [25:0] add_ln54_6_fu_458_p2;
wire   [25:0] y_7_fu_474_p3;
wire   [25:0] add_ln54_7_fu_482_p2;
wire   [25:0] y_8_fu_498_p3;
wire   [25:0] add_ln54_8_fu_506_p2;
wire   [25:0] y_9_fu_522_p3;
wire   [25:0] add_ln54_9_fu_530_p2;
wire   [25:0] y_31_fu_546_p3;
wire   [25:0] add_ln54_10_fu_554_p2;
wire   [25:0] y_10_fu_570_p3;
wire   [25:0] add_ln54_11_fu_578_p2;
wire   [25:0] y_11_fu_594_p3;
wire   [25:0] add_ln54_12_fu_602_p2;
wire   [25:0] y_12_fu_618_p3;
wire   [25:0] add_ln54_13_fu_626_p2;
wire   [25:0] y_13_fu_642_p3;
wire   [25:0] add_ln54_14_fu_650_p2;
wire   [25:0] y_14_fu_666_p3;
wire   [25:0] add_ln54_15_fu_674_p2;
wire   [25:0] y_15_fu_690_p3;
wire   [25:0] add_ln54_16_fu_698_p2;
wire   [25:0] y_16_fu_714_p3;
wire   [25:0] add_ln54_17_fu_722_p2;
wire   [25:0] y_17_fu_738_p3;
wire   [25:0] add_ln54_18_fu_746_p2;
wire   [25:0] y_18_fu_762_p3;
wire   [25:0] add_ln54_19_fu_770_p2;
wire   [25:0] y_19_fu_786_p3;
wire   [25:0] add_ln54_20_fu_794_p2;
wire   [25:0] y_20_fu_810_p3;
wire   [25:0] add_ln54_21_fu_818_p2;
wire   [25:0] y_21_fu_834_p3;
wire   [25:0] add_ln54_22_fu_842_p2;
wire   [25:0] y_22_fu_866_p3;
wire   [25:0] add_ln54_23_fu_874_p2;
wire   [25:0] y_23_fu_890_p3;
wire   [25:0] add_ln54_24_fu_898_p2;
wire   [25:0] y_24_fu_914_p3;
wire   [25:0] add_ln54_25_fu_922_p2;
wire   [25:0] y_25_fu_938_p3;
wire   [25:0] add_ln54_26_fu_946_p2;
wire   [25:0] y_26_fu_962_p3;
wire   [25:0] add_ln54_27_fu_970_p2;
wire   [25:0] y_27_fu_986_p3;
wire   [25:0] add_ln54_28_fu_994_p2;
wire   [25:0] y_28_fu_1010_p3;
wire   [25:0] add_ln54_29_fu_1018_p2;
wire   [25:0] y_29_fu_1034_p3;
wire   [25:0] add_ln54_30_fu_1042_p2;
wire   [15:0] shl_ln_fu_858_p3;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [15:0] ap_return_4_preg;
reg   [15:0] ap_return_5_preg;
reg   [15:0] ap_return_6_preg;
reg   [15:0] ap_return_7_preg;
reg   [15:0] ap_return_8_preg;
reg   [15:0] ap_return_9_preg;
reg   [15:0] ap_return_10_preg;
reg   [15:0] ap_return_11_preg;
reg   [15:0] ap_return_12_preg;
reg   [15:0] ap_return_13_preg;
reg   [15:0] ap_return_14_preg;
reg   [15:0] ap_return_15_preg;
reg   [15:0] ap_return_16_preg;
reg   [15:0] ap_return_17_preg;
reg   [15:0] ap_return_18_preg;
reg   [15:0] ap_return_19_preg;
reg   [15:0] ap_return_20_preg;
reg   [15:0] ap_return_21_preg;
reg   [15:0] ap_return_22_preg;
reg   [15:0] ap_return_23_preg;
reg   [15:0] ap_return_24_preg;
reg   [15:0] ap_return_25_preg;
reg   [15:0] ap_return_26_preg;
reg   [15:0] ap_return_27_preg;
reg   [15:0] ap_return_28_preg;
reg   [15:0] ap_return_29_preg;
reg   [15:0] ap_return_30_preg;
reg   [15:0] ap_return_31_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
#0 ap_return_4_preg = 16'd0;
#0 ap_return_5_preg = 16'd0;
#0 ap_return_6_preg = 16'd0;
#0 ap_return_7_preg = 16'd0;
#0 ap_return_8_preg = 16'd0;
#0 ap_return_9_preg = 16'd0;
#0 ap_return_10_preg = 16'd0;
#0 ap_return_11_preg = 16'd0;
#0 ap_return_12_preg = 16'd0;
#0 ap_return_13_preg = 16'd0;
#0 ap_return_14_preg = 16'd0;
#0 ap_return_15_preg = 16'd0;
#0 ap_return_16_preg = 16'd0;
#0 ap_return_17_preg = 16'd0;
#0 ap_return_18_preg = 16'd0;
#0 ap_return_19_preg = 16'd0;
#0 ap_return_20_preg = 16'd0;
#0 ap_return_21_preg = 16'd0;
#0 ap_return_22_preg = 16'd0;
#0 ap_return_23_preg = 16'd0;
#0 ap_return_24_preg = 16'd0;
#0 ap_return_25_preg = 16'd0;
#0 ap_return_26_preg = 16'd0;
#0 ap_return_27_preg = 16'd0;
#0 ap_return_28_preg = 16'd0;
#0 ap_return_29_preg = 16'd0;
#0 ap_return_30_preg = 16'd0;
#0 ap_return_31_preg = 16'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= {{add_ln54_fu_314_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= {{add_ln54_10_fu_554_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= {{add_ln54_11_fu_578_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= {{add_ln54_12_fu_602_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= {{add_ln54_13_fu_626_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= {{add_ln54_14_fu_650_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= {{add_ln54_15_fu_674_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_16_preg <= {{add_ln54_16_fu_698_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_17_preg <= {{add_ln54_17_fu_722_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_18_preg <= {{add_ln54_18_fu_746_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_19_preg <= {{add_ln54_19_fu_770_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= {{add_ln54_1_fu_338_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_20_preg <= {{add_ln54_20_fu_794_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_21_preg <= {{add_ln54_21_fu_818_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_22_preg <= {{add_ln54_22_fu_842_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_23_preg[1] <= 1'b0;
        ap_return_23_preg[2] <= 1'b0;
        ap_return_23_preg[3] <= 1'b0;
        ap_return_23_preg[4] <= 1'b0;
        ap_return_23_preg[5] <= 1'b0;
        ap_return_23_preg[6] <= 1'b0;
        ap_return_23_preg[7] <= 1'b0;
        ap_return_23_preg[8] <= 1'b0;
        ap_return_23_preg[9] <= 1'b0;
        ap_return_23_preg[10] <= 1'b0;
        ap_return_23_preg[11] <= 1'b0;
        ap_return_23_preg[12] <= 1'b0;
        ap_return_23_preg[13] <= 1'b0;
        ap_return_23_preg[14] <= 1'b0;
        ap_return_23_preg[15] <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                        ap_return_23_preg[15 : 1] <= shl_ln_fu_858_p3[15 : 1];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_24_preg <= {{add_ln54_23_fu_874_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_25_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_25_preg <= {{add_ln54_24_fu_898_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_26_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_26_preg <= {{add_ln54_25_fu_922_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_27_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_27_preg <= {{add_ln54_26_fu_946_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_28_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_28_preg <= {{add_ln54_27_fu_970_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_29_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_29_preg <= {{add_ln54_28_fu_994_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= {{add_ln54_2_fu_362_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_30_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_30_preg <= {{add_ln54_29_fu_1018_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_31_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_31_preg <= {{add_ln54_30_fu_1042_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= {{add_ln54_3_fu_386_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= {{add_ln54_4_fu_410_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= {{add_ln54_5_fu_434_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= {{add_ln54_6_fu_458_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= {{add_ln54_7_fu_482_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= {{add_ln54_8_fu_506_p2[25:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 16'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= {{add_ln54_9_fu_530_p2[25:10]}};
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = {{add_ln54_fu_314_p2[25:10]}};
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = {{add_ln54_1_fu_338_p2[25:10]}};
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = {{add_ln54_10_fu_554_p2[25:10]}};
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = {{add_ln54_11_fu_578_p2[25:10]}};
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = {{add_ln54_12_fu_602_p2[25:10]}};
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = {{add_ln54_13_fu_626_p2[25:10]}};
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = {{add_ln54_14_fu_650_p2[25:10]}};
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = {{add_ln54_15_fu_674_p2[25:10]}};
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_16 = {{add_ln54_16_fu_698_p2[25:10]}};
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_17 = {{add_ln54_17_fu_722_p2[25:10]}};
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_18 = {{add_ln54_18_fu_746_p2[25:10]}};
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_19 = {{add_ln54_19_fu_770_p2[25:10]}};
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = {{add_ln54_2_fu_362_p2[25:10]}};
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_20 = {{add_ln54_20_fu_794_p2[25:10]}};
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_21 = {{add_ln54_21_fu_818_p2[25:10]}};
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_22 = {{add_ln54_22_fu_842_p2[25:10]}};
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_23 = shl_ln_fu_858_p3;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_24 = {{add_ln54_23_fu_874_p2[25:10]}};
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_25 = {{add_ln54_24_fu_898_p2[25:10]}};
    end else begin
        ap_return_25 = ap_return_25_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_26 = {{add_ln54_25_fu_922_p2[25:10]}};
    end else begin
        ap_return_26 = ap_return_26_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_27 = {{add_ln54_26_fu_946_p2[25:10]}};
    end else begin
        ap_return_27 = ap_return_27_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_28 = {{add_ln54_27_fu_970_p2[25:10]}};
    end else begin
        ap_return_28 = ap_return_28_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_29 = {{add_ln54_28_fu_994_p2[25:10]}};
    end else begin
        ap_return_29 = ap_return_29_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = {{add_ln54_3_fu_386_p2[25:10]}};
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_30 = {{add_ln54_29_fu_1018_p2[25:10]}};
    end else begin
        ap_return_30 = ap_return_30_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_31 = {{add_ln54_30_fu_1042_p2[25:10]}};
    end else begin
        ap_return_31 = ap_return_31_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = {{add_ln54_4_fu_410_p2[25:10]}};
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = {{add_ln54_5_fu_434_p2[25:10]}};
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = {{add_ln54_6_fu_458_p2[25:10]}};
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = {{add_ln54_7_fu_482_p2[25:10]}};
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = {{add_ln54_8_fu_506_p2[25:10]}};
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = {{add_ln54_9_fu_530_p2[25:10]}};
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln54_10_fu_554_p2 = (y_31_fu_546_p3 + 26'd327680);

assign add_ln54_11_fu_578_p2 = (y_10_fu_570_p3 + 26'd327680);

assign add_ln54_12_fu_602_p2 = ($signed(y_11_fu_594_p3) + $signed(26'd67043328));

assign add_ln54_13_fu_626_p2 = ($signed(y_12_fu_618_p3) + $signed(26'd66912256));

assign add_ln54_14_fu_650_p2 = (y_13_fu_642_p3 + 26'd327680);

assign add_ln54_15_fu_674_p2 = (y_14_fu_666_p3 + 26'd196608);

assign add_ln54_16_fu_698_p2 = (y_15_fu_690_p3 + 26'd196608);

assign add_ln54_17_fu_722_p2 = (y_16_fu_714_p3 + 26'd524288);

assign add_ln54_18_fu_746_p2 = (y_17_fu_738_p3 + 26'd196608);

assign add_ln54_19_fu_770_p2 = ($signed(y_18_fu_762_p3) + $signed(26'd66977792));

assign add_ln54_1_fu_338_p2 = ($signed(y_1_fu_330_p3) + $signed(26'd66912256));

assign add_ln54_20_fu_794_p2 = (y_19_fu_786_p3 + 26'd196608);

assign add_ln54_21_fu_818_p2 = (y_20_fu_810_p3 + 26'd196608);

assign add_ln54_22_fu_842_p2 = (y_21_fu_834_p3 + 26'd262144);

assign add_ln54_23_fu_874_p2 = (y_22_fu_866_p3 + 26'd196608);

assign add_ln54_24_fu_898_p2 = (y_23_fu_890_p3 + 26'd327680);

assign add_ln54_25_fu_922_p2 = ($signed(y_24_fu_914_p3) + $signed(26'd67043328));

assign add_ln54_26_fu_946_p2 = ($signed(y_25_fu_938_p3) + $signed(26'd66912256));

assign add_ln54_27_fu_970_p2 = ($signed(y_26_fu_962_p3) + $signed(26'd66846720));

assign add_ln54_28_fu_994_p2 = ($signed(y_27_fu_986_p3) + $signed(26'd66977792));

assign add_ln54_29_fu_1018_p2 = (y_28_fu_1010_p3 + 26'd196608);

assign add_ln54_2_fu_362_p2 = (y_2_fu_354_p3 + 26'd262144);

assign add_ln54_30_fu_1042_p2 = (y_29_fu_1034_p3 + 26'd196608);

assign add_ln54_3_fu_386_p2 = ($signed(y_3_fu_378_p3) + $signed(26'd66977792));

assign add_ln54_4_fu_410_p2 = ($signed(y_4_fu_402_p3) + $signed(26'd66650112));

assign add_ln54_5_fu_434_p2 = ($signed(y_5_fu_426_p3) + $signed(26'd67043328));

assign add_ln54_6_fu_458_p2 = (y_6_fu_450_p3 + 26'd196608);

assign add_ln54_7_fu_482_p2 = (y_7_fu_474_p3 + 26'd262144);

assign add_ln54_8_fu_506_p2 = (y_8_fu_498_p3 + 26'd327680);

assign add_ln54_9_fu_530_p2 = (y_9_fu_522_p3 + 26'd196608);

assign add_ln54_fu_314_p2 = (y_fu_306_p3 + 26'd327680);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign shl_ln_fu_858_p3 = {{p_read23}, {1'd0}};

assign y_10_fu_570_p3 = {{p_read11}, {11'd0}};

assign y_11_fu_594_p3 = {{p_read12}, {11'd0}};

assign y_12_fu_618_p3 = {{p_read13}, {11'd0}};

assign y_13_fu_642_p3 = {{p_read14}, {11'd0}};

assign y_14_fu_666_p3 = {{p_read15}, {11'd0}};

assign y_15_fu_690_p3 = {{p_read16}, {11'd0}};

assign y_16_fu_714_p3 = {{p_read17}, {11'd0}};

assign y_17_fu_738_p3 = {{p_read18}, {11'd0}};

assign y_18_fu_762_p3 = {{p_read19}, {11'd0}};

assign y_19_fu_786_p3 = {{p_read20}, {11'd0}};

assign y_1_fu_330_p3 = {{p_read1}, {11'd0}};

assign y_20_fu_810_p3 = {{p_read21}, {11'd0}};

assign y_21_fu_834_p3 = {{p_read22}, {11'd0}};

assign y_22_fu_866_p3 = {{p_read24}, {11'd0}};

assign y_23_fu_890_p3 = {{p_read25}, {11'd0}};

assign y_24_fu_914_p3 = {{p_read26}, {11'd0}};

assign y_25_fu_938_p3 = {{p_read27}, {11'd0}};

assign y_26_fu_962_p3 = {{p_read28}, {11'd0}};

assign y_27_fu_986_p3 = {{p_read29}, {11'd0}};

assign y_28_fu_1010_p3 = {{p_read30}, {11'd0}};

assign y_29_fu_1034_p3 = {{p_read31}, {11'd0}};

assign y_2_fu_354_p3 = {{p_read2}, {11'd0}};

assign y_31_fu_546_p3 = {{p_read10}, {11'd0}};

assign y_3_fu_378_p3 = {{p_read3}, {11'd0}};

assign y_4_fu_402_p3 = {{p_read4}, {11'd0}};

assign y_5_fu_426_p3 = {{p_read5}, {11'd0}};

assign y_6_fu_450_p3 = {{p_read6}, {11'd0}};

assign y_7_fu_474_p3 = {{p_read7}, {11'd0}};

assign y_8_fu_498_p3 = {{p_read8}, {11'd0}};

assign y_9_fu_522_p3 = {{p_read9}, {11'd0}};

assign y_fu_306_p3 = {{p_read}, {11'd0}};

always @ (posedge ap_clk) begin
    ap_return_23_preg[0] <= 1'b0;
end

endmodule //myproject_normalize_ap_fixed_16_10_5_3_0_ap_fixed_16_6_5_3_0_config11_s
