// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read19;
input  [7:0] p_read20;
input  [7:0] p_read21;
input  [7:0] p_read22;
input  [7:0] p_read23;
input  [7:0] p_read24;
input  [7:0] p_read25;
input  [7:0] p_read26;
input  [7:0] p_read27;
input  [7:0] p_read28;
input  [7:0] p_read29;
input  [7:0] p_read30;
input  [7:0] p_read31;
output  [11:0] ap_return;

reg ap_idle;
reg[11:0] ap_return;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln46_fu_1207_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] w8_address0;
reg    w8_ce0;
wire   [10:0] w8_q0;
reg   [0:0] do_init_reg_321;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] w_index6_reg_336;
reg   [7:0] p_read32_phi_reg_798;
reg   [7:0] p_read133_phi_reg_810;
reg   [7:0] p_read234_phi_reg_822;
reg   [7:0] p_read335_phi_reg_834;
reg   [7:0] p_read436_phi_reg_846;
reg   [7:0] p_read537_phi_reg_858;
reg   [7:0] p_read638_phi_reg_870;
reg   [7:0] p_read739_phi_reg_882;
reg   [7:0] p_read840_phi_reg_894;
reg   [7:0] p_read941_phi_reg_906;
reg   [7:0] p_read1042_phi_reg_918;
reg   [7:0] p_read1143_phi_reg_930;
reg   [7:0] p_read1244_phi_reg_942;
reg   [7:0] p_read1345_phi_reg_954;
reg   [7:0] p_read1446_phi_reg_966;
reg   [7:0] p_read1547_phi_reg_978;
reg   [7:0] p_read1648_phi_reg_990;
reg   [7:0] p_read1749_phi_reg_1002;
reg   [7:0] p_read1850_phi_reg_1014;
reg   [7:0] p_read1951_phi_reg_1026;
reg   [7:0] p_read2052_phi_reg_1038;
reg   [7:0] p_read2153_phi_reg_1050;
reg   [7:0] p_read2254_phi_reg_1062;
reg   [7:0] p_read2355_phi_reg_1074;
reg   [7:0] p_read2456_phi_reg_1086;
reg   [7:0] p_read2557_phi_reg_1098;
reg   [7:0] p_read2658_phi_reg_1110;
reg   [7:0] p_read2759_phi_reg_1122;
reg   [7:0] p_read2860_phi_reg_1134;
reg   [7:0] p_read2961_phi_reg_1146;
reg   [7:0] p_read3062_phi_reg_1158;
reg   [7:0] p_read3163_phi_reg_1170;
reg   [15:0] empty_reg_1182;
reg   [0:0] ap_phi_mux_do_init_phi_fu_324_p6;
wire   [4:0] w_index_fu_1201_p2;
reg   [4:0] w_index_reg_1487;
reg   [0:0] icmp_ln46_reg_1492;
reg   [0:0] icmp_ln46_reg_1492_pp0_iter1_reg;
reg   [0:0] icmp_ln46_reg_1492_pp0_iter2_reg;
wire   [7:0] a_fu_1213_p34;
reg   [7:0] a_reg_1496;
reg  signed [10:0] w_reg_1501;
reg   [10:0] trunc_ln4_reg_1506;
wire   [15:0] add_ln58_fu_1308_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [4:0] ap_phi_mux_w_index6_phi_fu_339_p6;
reg   [7:0] ap_phi_mux_p_read32_phi_phi_fu_802_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read32_phi_reg_798;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read32_phi_reg_798;
reg   [7:0] ap_phi_mux_p_read133_phi_phi_fu_814_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read133_phi_reg_810;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read133_phi_reg_810;
reg   [7:0] ap_phi_mux_p_read234_phi_phi_fu_826_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read234_phi_reg_822;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read234_phi_reg_822;
reg   [7:0] ap_phi_mux_p_read335_phi_phi_fu_838_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read335_phi_reg_834;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read335_phi_reg_834;
reg   [7:0] ap_phi_mux_p_read436_phi_phi_fu_850_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read436_phi_reg_846;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read436_phi_reg_846;
reg   [7:0] ap_phi_mux_p_read537_phi_phi_fu_862_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read537_phi_reg_858;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read537_phi_reg_858;
reg   [7:0] ap_phi_mux_p_read638_phi_phi_fu_874_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read638_phi_reg_870;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read638_phi_reg_870;
reg   [7:0] ap_phi_mux_p_read739_phi_phi_fu_886_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read739_phi_reg_882;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read739_phi_reg_882;
reg   [7:0] ap_phi_mux_p_read840_phi_phi_fu_898_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read840_phi_reg_894;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read840_phi_reg_894;
reg   [7:0] ap_phi_mux_p_read941_phi_phi_fu_910_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read941_phi_reg_906;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read941_phi_reg_906;
reg   [7:0] ap_phi_mux_p_read1042_phi_phi_fu_922_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1042_phi_reg_918;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918;
reg   [7:0] ap_phi_mux_p_read1143_phi_phi_fu_934_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1143_phi_reg_930;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930;
reg   [7:0] ap_phi_mux_p_read1244_phi_phi_fu_946_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1244_phi_reg_942;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942;
reg   [7:0] ap_phi_mux_p_read1345_phi_phi_fu_958_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1345_phi_reg_954;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954;
reg   [7:0] ap_phi_mux_p_read1446_phi_phi_fu_970_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1446_phi_reg_966;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966;
reg   [7:0] ap_phi_mux_p_read1547_phi_phi_fu_982_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1547_phi_reg_978;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978;
reg   [7:0] ap_phi_mux_p_read1648_phi_phi_fu_994_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1648_phi_reg_990;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990;
reg   [7:0] ap_phi_mux_p_read1749_phi_phi_fu_1006_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1749_phi_reg_1002;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002;
reg   [7:0] ap_phi_mux_p_read1850_phi_phi_fu_1018_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1850_phi_reg_1014;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014;
reg   [7:0] ap_phi_mux_p_read1951_phi_phi_fu_1030_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1951_phi_reg_1026;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026;
reg   [7:0] ap_phi_mux_p_read2052_phi_phi_fu_1042_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2052_phi_reg_1038;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038;
reg   [7:0] ap_phi_mux_p_read2153_phi_phi_fu_1054_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2153_phi_reg_1050;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050;
reg   [7:0] ap_phi_mux_p_read2254_phi_phi_fu_1066_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2254_phi_reg_1062;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062;
reg   [7:0] ap_phi_mux_p_read2355_phi_phi_fu_1078_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2355_phi_reg_1074;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074;
reg   [7:0] ap_phi_mux_p_read2456_phi_phi_fu_1090_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2456_phi_reg_1086;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086;
reg   [7:0] ap_phi_mux_p_read2557_phi_phi_fu_1102_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2557_phi_reg_1098;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098;
reg   [7:0] ap_phi_mux_p_read2658_phi_phi_fu_1114_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2658_phi_reg_1110;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110;
reg   [7:0] ap_phi_mux_p_read2759_phi_phi_fu_1126_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2759_phi_reg_1122;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122;
reg   [7:0] ap_phi_mux_p_read2860_phi_phi_fu_1138_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2860_phi_reg_1134;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134;
reg   [7:0] ap_phi_mux_p_read2961_phi_phi_fu_1150_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read2961_phi_reg_1146;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146;
reg   [7:0] ap_phi_mux_p_read3062_phi_phi_fu_1162_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read3062_phi_reg_1158;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158;
reg   [7:0] ap_phi_mux_p_read3163_phi_phi_fu_1174_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read3163_phi_reg_1170;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170;
reg   [15:0] ap_phi_mux_empty_phi_fu_1186_p6;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg    ap_loop_init_pp0_iter3_reg;
wire   [63:0] zext_ln46_fu_1196_p1;
wire   [7:0] mul_ln73_fu_1289_p1;
wire   [18:0] mul_ln73_fu_1289_p2;
wire  signed [15:0] sext_ln58_fu_1305_p1;
wire   [11:0] trunc_ln46_fu_1314_p1;
reg   [11:0] ap_return_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [18:0] mul_ln73_fu_1289_p10;
reg    ap_condition_310;
reg    ap_condition_331;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_preg = 12'd0;
end

myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s_w8_ROM_NP_dEe #(
    .DataWidth( 11 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
w8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w8_address0),
    .ce0(w8_ce0),
    .q0(w8_q0)
);

myproject_mux_32_5_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_32_5_8_1_1_U395(
    .din0(ap_phi_mux_p_read32_phi_phi_fu_802_p4),
    .din1(ap_phi_mux_p_read133_phi_phi_fu_814_p4),
    .din2(ap_phi_mux_p_read234_phi_phi_fu_826_p4),
    .din3(ap_phi_mux_p_read335_phi_phi_fu_838_p4),
    .din4(ap_phi_mux_p_read436_phi_phi_fu_850_p4),
    .din5(ap_phi_mux_p_read537_phi_phi_fu_862_p4),
    .din6(ap_phi_mux_p_read638_phi_phi_fu_874_p4),
    .din7(ap_phi_mux_p_read739_phi_phi_fu_886_p4),
    .din8(ap_phi_mux_p_read840_phi_phi_fu_898_p4),
    .din9(ap_phi_mux_p_read941_phi_phi_fu_910_p4),
    .din10(ap_phi_mux_p_read1042_phi_phi_fu_922_p4),
    .din11(ap_phi_mux_p_read1143_phi_phi_fu_934_p4),
    .din12(ap_phi_mux_p_read1244_phi_phi_fu_946_p4),
    .din13(ap_phi_mux_p_read1345_phi_phi_fu_958_p4),
    .din14(ap_phi_mux_p_read1446_phi_phi_fu_970_p4),
    .din15(ap_phi_mux_p_read1547_phi_phi_fu_982_p4),
    .din16(ap_phi_mux_p_read1648_phi_phi_fu_994_p4),
    .din17(ap_phi_mux_p_read1749_phi_phi_fu_1006_p4),
    .din18(ap_phi_mux_p_read1850_phi_phi_fu_1018_p4),
    .din19(ap_phi_mux_p_read1951_phi_phi_fu_1030_p4),
    .din20(ap_phi_mux_p_read2052_phi_phi_fu_1042_p4),
    .din21(ap_phi_mux_p_read2153_phi_phi_fu_1054_p4),
    .din22(ap_phi_mux_p_read2254_phi_phi_fu_1066_p4),
    .din23(ap_phi_mux_p_read2355_phi_phi_fu_1078_p4),
    .din24(ap_phi_mux_p_read2456_phi_phi_fu_1090_p4),
    .din25(ap_phi_mux_p_read2557_phi_phi_fu_1102_p4),
    .din26(ap_phi_mux_p_read2658_phi_phi_fu_1114_p4),
    .din27(ap_phi_mux_p_read2759_phi_phi_fu_1126_p4),
    .din28(ap_phi_mux_p_read2860_phi_phi_fu_1138_p4),
    .din29(ap_phi_mux_p_read2961_phi_phi_fu_1150_p4),
    .din30(ap_phi_mux_p_read3062_phi_phi_fu_1162_p4),
    .din31(ap_phi_mux_p_read3163_phi_phi_fu_1174_p4),
    .din32(w_index6_reg_336),
    .dout(a_fu_1213_p34)
);

myproject_mul_11s_8ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 19 ))
mul_11s_8ns_19_1_1_U396(
    .din0(w_reg_1501),
    .din1(mul_ln73_fu_1289_p1),
    .dout(mul_ln73_fu_1289_p2)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 12'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1492_pp0_iter2_reg == 1'd1))) begin
            ap_return_preg <= trunc_ln46_fu_1314_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918 <= p_read10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918 <= ap_phi_reg_pp0_iter0_p_read1042_phi_reg_918;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930 <= p_read11;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930 <= ap_phi_reg_pp0_iter0_p_read1143_phi_reg_930;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942 <= p_read12;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942 <= ap_phi_reg_pp0_iter0_p_read1244_phi_reg_942;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read133_phi_reg_810 <= p_read1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read133_phi_reg_810 <= ap_phi_reg_pp0_iter0_p_read133_phi_reg_810;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954 <= p_read13;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954 <= ap_phi_reg_pp0_iter0_p_read1345_phi_reg_954;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966 <= p_read14;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966 <= ap_phi_reg_pp0_iter0_p_read1446_phi_reg_966;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978 <= p_read15;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978 <= ap_phi_reg_pp0_iter0_p_read1547_phi_reg_978;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990 <= p_read16;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990 <= ap_phi_reg_pp0_iter0_p_read1648_phi_reg_990;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002 <= p_read17;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002 <= ap_phi_reg_pp0_iter0_p_read1749_phi_reg_1002;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014 <= p_read18;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014 <= ap_phi_reg_pp0_iter0_p_read1850_phi_reg_1014;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026 <= p_read19;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026 <= ap_phi_reg_pp0_iter0_p_read1951_phi_reg_1026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038 <= p_read20;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038 <= ap_phi_reg_pp0_iter0_p_read2052_phi_reg_1038;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050 <= p_read21;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050 <= ap_phi_reg_pp0_iter0_p_read2153_phi_reg_1050;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062 <= p_read22;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062 <= ap_phi_reg_pp0_iter0_p_read2254_phi_reg_1062;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read234_phi_reg_822 <= p_read2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read234_phi_reg_822 <= ap_phi_reg_pp0_iter0_p_read234_phi_reg_822;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074 <= p_read23;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074 <= ap_phi_reg_pp0_iter0_p_read2355_phi_reg_1074;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086 <= p_read24;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086 <= ap_phi_reg_pp0_iter0_p_read2456_phi_reg_1086;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098 <= p_read25;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098 <= ap_phi_reg_pp0_iter0_p_read2557_phi_reg_1098;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110 <= p_read26;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110 <= ap_phi_reg_pp0_iter0_p_read2658_phi_reg_1110;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122 <= p_read27;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122 <= ap_phi_reg_pp0_iter0_p_read2759_phi_reg_1122;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134 <= p_read28;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134 <= ap_phi_reg_pp0_iter0_p_read2860_phi_reg_1134;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146 <= p_read29;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146 <= ap_phi_reg_pp0_iter0_p_read2961_phi_reg_1146;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158 <= p_read30;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158 <= ap_phi_reg_pp0_iter0_p_read3062_phi_reg_1158;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170 <= p_read31;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170 <= ap_phi_reg_pp0_iter0_p_read3163_phi_reg_1170;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read32_phi_reg_798 <= p_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read32_phi_reg_798 <= ap_phi_reg_pp0_iter0_p_read32_phi_reg_798;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read335_phi_reg_834 <= p_read3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read335_phi_reg_834 <= ap_phi_reg_pp0_iter0_p_read335_phi_reg_834;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read436_phi_reg_846 <= p_read4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read436_phi_reg_846 <= ap_phi_reg_pp0_iter0_p_read436_phi_reg_846;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read537_phi_reg_858 <= p_read5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read537_phi_reg_858 <= ap_phi_reg_pp0_iter0_p_read537_phi_reg_858;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read638_phi_reg_870 <= p_read6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read638_phi_reg_870 <= ap_phi_reg_pp0_iter0_p_read638_phi_reg_870;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read739_phi_reg_882 <= p_read7;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read739_phi_reg_882 <= ap_phi_reg_pp0_iter0_p_read739_phi_reg_882;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read840_phi_reg_894 <= p_read8;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read840_phi_reg_894 <= ap_phi_reg_pp0_iter0_p_read840_phi_reg_894;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((ap_phi_mux_do_init_phi_fu_324_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read941_phi_reg_906 <= p_read9;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read941_phi_reg_906 <= ap_phi_reg_pp0_iter0_p_read941_phi_reg_906;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_321 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1492 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        do_init_reg_321 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((icmp_ln46_reg_1492_pp0_iter2_reg == 1'd1)) begin
            empty_reg_1182 <= 16'd11;
        end else if ((icmp_ln46_reg_1492_pp0_iter2_reg == 1'd0)) begin
            empty_reg_1182 <= add_ln58_fu_1308_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1042_phi_reg_918 <= p_read1042_phi_reg_918;
        end else if ((1'b1 == 1'b1)) begin
            p_read1042_phi_reg_918 <= ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1143_phi_reg_930 <= p_read1143_phi_reg_930;
        end else if ((1'b1 == 1'b1)) begin
            p_read1143_phi_reg_930 <= ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1244_phi_reg_942 <= p_read1244_phi_reg_942;
        end else if ((1'b1 == 1'b1)) begin
            p_read1244_phi_reg_942 <= ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read133_phi_reg_810 <= p_read133_phi_reg_810;
        end else if ((1'b1 == 1'b1)) begin
            p_read133_phi_reg_810 <= ap_phi_reg_pp0_iter1_p_read133_phi_reg_810;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1345_phi_reg_954 <= p_read1345_phi_reg_954;
        end else if ((1'b1 == 1'b1)) begin
            p_read1345_phi_reg_954 <= ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1446_phi_reg_966 <= p_read1446_phi_reg_966;
        end else if ((1'b1 == 1'b1)) begin
            p_read1446_phi_reg_966 <= ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1547_phi_reg_978 <= p_read1547_phi_reg_978;
        end else if ((1'b1 == 1'b1)) begin
            p_read1547_phi_reg_978 <= ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1648_phi_reg_990 <= p_read1648_phi_reg_990;
        end else if ((1'b1 == 1'b1)) begin
            p_read1648_phi_reg_990 <= ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1749_phi_reg_1002 <= p_read1749_phi_reg_1002;
        end else if ((1'b1 == 1'b1)) begin
            p_read1749_phi_reg_1002 <= ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1850_phi_reg_1014 <= p_read1850_phi_reg_1014;
        end else if ((1'b1 == 1'b1)) begin
            p_read1850_phi_reg_1014 <= ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read1951_phi_reg_1026 <= p_read1951_phi_reg_1026;
        end else if ((1'b1 == 1'b1)) begin
            p_read1951_phi_reg_1026 <= ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2052_phi_reg_1038 <= p_read2052_phi_reg_1038;
        end else if ((1'b1 == 1'b1)) begin
            p_read2052_phi_reg_1038 <= ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2153_phi_reg_1050 <= p_read2153_phi_reg_1050;
        end else if ((1'b1 == 1'b1)) begin
            p_read2153_phi_reg_1050 <= ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2254_phi_reg_1062 <= p_read2254_phi_reg_1062;
        end else if ((1'b1 == 1'b1)) begin
            p_read2254_phi_reg_1062 <= ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read234_phi_reg_822 <= p_read234_phi_reg_822;
        end else if ((1'b1 == 1'b1)) begin
            p_read234_phi_reg_822 <= ap_phi_reg_pp0_iter1_p_read234_phi_reg_822;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2355_phi_reg_1074 <= p_read2355_phi_reg_1074;
        end else if ((1'b1 == 1'b1)) begin
            p_read2355_phi_reg_1074 <= ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2456_phi_reg_1086 <= p_read2456_phi_reg_1086;
        end else if ((1'b1 == 1'b1)) begin
            p_read2456_phi_reg_1086 <= ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2557_phi_reg_1098 <= p_read2557_phi_reg_1098;
        end else if ((1'b1 == 1'b1)) begin
            p_read2557_phi_reg_1098 <= ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2658_phi_reg_1110 <= p_read2658_phi_reg_1110;
        end else if ((1'b1 == 1'b1)) begin
            p_read2658_phi_reg_1110 <= ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2759_phi_reg_1122 <= p_read2759_phi_reg_1122;
        end else if ((1'b1 == 1'b1)) begin
            p_read2759_phi_reg_1122 <= ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2860_phi_reg_1134 <= p_read2860_phi_reg_1134;
        end else if ((1'b1 == 1'b1)) begin
            p_read2860_phi_reg_1134 <= ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read2961_phi_reg_1146 <= p_read2961_phi_reg_1146;
        end else if ((1'b1 == 1'b1)) begin
            p_read2961_phi_reg_1146 <= ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read3062_phi_reg_1158 <= p_read3062_phi_reg_1158;
        end else if ((1'b1 == 1'b1)) begin
            p_read3062_phi_reg_1158 <= ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read3163_phi_reg_1170 <= p_read3163_phi_reg_1170;
        end else if ((1'b1 == 1'b1)) begin
            p_read3163_phi_reg_1170 <= ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read32_phi_reg_798 <= p_read32_phi_reg_798;
        end else if ((1'b1 == 1'b1)) begin
            p_read32_phi_reg_798 <= ap_phi_reg_pp0_iter1_p_read32_phi_reg_798;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read335_phi_reg_834 <= p_read335_phi_reg_834;
        end else if ((1'b1 == 1'b1)) begin
            p_read335_phi_reg_834 <= ap_phi_reg_pp0_iter1_p_read335_phi_reg_834;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read436_phi_reg_846 <= p_read436_phi_reg_846;
        end else if ((1'b1 == 1'b1)) begin
            p_read436_phi_reg_846 <= ap_phi_reg_pp0_iter1_p_read436_phi_reg_846;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read537_phi_reg_858 <= p_read537_phi_reg_858;
        end else if ((1'b1 == 1'b1)) begin
            p_read537_phi_reg_858 <= ap_phi_reg_pp0_iter1_p_read537_phi_reg_858;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read638_phi_reg_870 <= p_read638_phi_reg_870;
        end else if ((1'b1 == 1'b1)) begin
            p_read638_phi_reg_870 <= ap_phi_reg_pp0_iter1_p_read638_phi_reg_870;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read739_phi_reg_882 <= p_read739_phi_reg_882;
        end else if ((1'b1 == 1'b1)) begin
            p_read739_phi_reg_882 <= ap_phi_reg_pp0_iter1_p_read739_phi_reg_882;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read840_phi_reg_894 <= p_read840_phi_reg_894;
        end else if ((1'b1 == 1'b1)) begin
            p_read840_phi_reg_894 <= ap_phi_reg_pp0_iter1_p_read840_phi_reg_894;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_331)) begin
        if ((do_init_reg_321 == 1'd0)) begin
            p_read941_phi_reg_906 <= p_read941_phi_reg_906;
        end else if ((1'b1 == 1'b1)) begin
            p_read941_phi_reg_906 <= ap_phi_reg_pp0_iter1_p_read941_phi_reg_906;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index6_reg_336 <= w_index_reg_1487;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1492 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        w_index6_reg_336 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_1496 <= a_fu_1213_p34;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln46_reg_1492 <= icmp_ln46_fu_1207_p2;
        icmp_ln46_reg_1492_pp0_iter1_reg <= icmp_ln46_reg_1492;
        w_reg_1501 <= w8_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
        icmp_ln46_reg_1492_pp0_iter2_reg <= icmp_ln46_reg_1492_pp0_iter1_reg;
        trunc_ln4_reg_1506 <= {{mul_ln73_fu_1289_p2[18:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1487 <= w_index_fu_1201_p2;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_1207_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_do_init_phi_fu_324_p6 = 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1492 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_do_init_phi_fu_324_p6 = 1'd1;
    end else begin
        ap_phi_mux_do_init_phi_fu_324_p6 = do_init_reg_321;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter3_reg == 1'b1)) begin
        ap_phi_mux_empty_phi_fu_1186_p6 = 16'd11;
    end else begin
        ap_phi_mux_empty_phi_fu_1186_p6 = empty_reg_1182;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1042_phi_phi_fu_922_p4 = p_read1042_phi_reg_918;
    end else begin
        ap_phi_mux_p_read1042_phi_phi_fu_922_p4 = ap_phi_reg_pp0_iter1_p_read1042_phi_reg_918;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1143_phi_phi_fu_934_p4 = p_read1143_phi_reg_930;
    end else begin
        ap_phi_mux_p_read1143_phi_phi_fu_934_p4 = ap_phi_reg_pp0_iter1_p_read1143_phi_reg_930;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1244_phi_phi_fu_946_p4 = p_read1244_phi_reg_942;
    end else begin
        ap_phi_mux_p_read1244_phi_phi_fu_946_p4 = ap_phi_reg_pp0_iter1_p_read1244_phi_reg_942;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read133_phi_phi_fu_814_p4 = p_read133_phi_reg_810;
    end else begin
        ap_phi_mux_p_read133_phi_phi_fu_814_p4 = ap_phi_reg_pp0_iter1_p_read133_phi_reg_810;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1345_phi_phi_fu_958_p4 = p_read1345_phi_reg_954;
    end else begin
        ap_phi_mux_p_read1345_phi_phi_fu_958_p4 = ap_phi_reg_pp0_iter1_p_read1345_phi_reg_954;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1446_phi_phi_fu_970_p4 = p_read1446_phi_reg_966;
    end else begin
        ap_phi_mux_p_read1446_phi_phi_fu_970_p4 = ap_phi_reg_pp0_iter1_p_read1446_phi_reg_966;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1547_phi_phi_fu_982_p4 = p_read1547_phi_reg_978;
    end else begin
        ap_phi_mux_p_read1547_phi_phi_fu_982_p4 = ap_phi_reg_pp0_iter1_p_read1547_phi_reg_978;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1648_phi_phi_fu_994_p4 = p_read1648_phi_reg_990;
    end else begin
        ap_phi_mux_p_read1648_phi_phi_fu_994_p4 = ap_phi_reg_pp0_iter1_p_read1648_phi_reg_990;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1749_phi_phi_fu_1006_p4 = p_read1749_phi_reg_1002;
    end else begin
        ap_phi_mux_p_read1749_phi_phi_fu_1006_p4 = ap_phi_reg_pp0_iter1_p_read1749_phi_reg_1002;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1850_phi_phi_fu_1018_p4 = p_read1850_phi_reg_1014;
    end else begin
        ap_phi_mux_p_read1850_phi_phi_fu_1018_p4 = ap_phi_reg_pp0_iter1_p_read1850_phi_reg_1014;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read1951_phi_phi_fu_1030_p4 = p_read1951_phi_reg_1026;
    end else begin
        ap_phi_mux_p_read1951_phi_phi_fu_1030_p4 = ap_phi_reg_pp0_iter1_p_read1951_phi_reg_1026;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2052_phi_phi_fu_1042_p4 = p_read2052_phi_reg_1038;
    end else begin
        ap_phi_mux_p_read2052_phi_phi_fu_1042_p4 = ap_phi_reg_pp0_iter1_p_read2052_phi_reg_1038;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2153_phi_phi_fu_1054_p4 = p_read2153_phi_reg_1050;
    end else begin
        ap_phi_mux_p_read2153_phi_phi_fu_1054_p4 = ap_phi_reg_pp0_iter1_p_read2153_phi_reg_1050;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2254_phi_phi_fu_1066_p4 = p_read2254_phi_reg_1062;
    end else begin
        ap_phi_mux_p_read2254_phi_phi_fu_1066_p4 = ap_phi_reg_pp0_iter1_p_read2254_phi_reg_1062;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read234_phi_phi_fu_826_p4 = p_read234_phi_reg_822;
    end else begin
        ap_phi_mux_p_read234_phi_phi_fu_826_p4 = ap_phi_reg_pp0_iter1_p_read234_phi_reg_822;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2355_phi_phi_fu_1078_p4 = p_read2355_phi_reg_1074;
    end else begin
        ap_phi_mux_p_read2355_phi_phi_fu_1078_p4 = ap_phi_reg_pp0_iter1_p_read2355_phi_reg_1074;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2456_phi_phi_fu_1090_p4 = p_read2456_phi_reg_1086;
    end else begin
        ap_phi_mux_p_read2456_phi_phi_fu_1090_p4 = ap_phi_reg_pp0_iter1_p_read2456_phi_reg_1086;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2557_phi_phi_fu_1102_p4 = p_read2557_phi_reg_1098;
    end else begin
        ap_phi_mux_p_read2557_phi_phi_fu_1102_p4 = ap_phi_reg_pp0_iter1_p_read2557_phi_reg_1098;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2658_phi_phi_fu_1114_p4 = p_read2658_phi_reg_1110;
    end else begin
        ap_phi_mux_p_read2658_phi_phi_fu_1114_p4 = ap_phi_reg_pp0_iter1_p_read2658_phi_reg_1110;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2759_phi_phi_fu_1126_p4 = p_read2759_phi_reg_1122;
    end else begin
        ap_phi_mux_p_read2759_phi_phi_fu_1126_p4 = ap_phi_reg_pp0_iter1_p_read2759_phi_reg_1122;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2860_phi_phi_fu_1138_p4 = p_read2860_phi_reg_1134;
    end else begin
        ap_phi_mux_p_read2860_phi_phi_fu_1138_p4 = ap_phi_reg_pp0_iter1_p_read2860_phi_reg_1134;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read2961_phi_phi_fu_1150_p4 = p_read2961_phi_reg_1146;
    end else begin
        ap_phi_mux_p_read2961_phi_phi_fu_1150_p4 = ap_phi_reg_pp0_iter1_p_read2961_phi_reg_1146;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read3062_phi_phi_fu_1162_p4 = p_read3062_phi_reg_1158;
    end else begin
        ap_phi_mux_p_read3062_phi_phi_fu_1162_p4 = ap_phi_reg_pp0_iter1_p_read3062_phi_reg_1158;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read3163_phi_phi_fu_1174_p4 = p_read3163_phi_reg_1170;
    end else begin
        ap_phi_mux_p_read3163_phi_phi_fu_1174_p4 = ap_phi_reg_pp0_iter1_p_read3163_phi_reg_1170;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read32_phi_phi_fu_802_p4 = p_read32_phi_reg_798;
    end else begin
        ap_phi_mux_p_read32_phi_phi_fu_802_p4 = ap_phi_reg_pp0_iter1_p_read32_phi_reg_798;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read335_phi_phi_fu_838_p4 = p_read335_phi_reg_834;
    end else begin
        ap_phi_mux_p_read335_phi_phi_fu_838_p4 = ap_phi_reg_pp0_iter1_p_read335_phi_reg_834;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read436_phi_phi_fu_850_p4 = p_read436_phi_reg_846;
    end else begin
        ap_phi_mux_p_read436_phi_phi_fu_850_p4 = ap_phi_reg_pp0_iter1_p_read436_phi_reg_846;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read537_phi_phi_fu_862_p4 = p_read537_phi_reg_858;
    end else begin
        ap_phi_mux_p_read537_phi_phi_fu_862_p4 = ap_phi_reg_pp0_iter1_p_read537_phi_reg_858;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read638_phi_phi_fu_874_p4 = p_read638_phi_reg_870;
    end else begin
        ap_phi_mux_p_read638_phi_phi_fu_874_p4 = ap_phi_reg_pp0_iter1_p_read638_phi_reg_870;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read739_phi_phi_fu_886_p4 = p_read739_phi_reg_882;
    end else begin
        ap_phi_mux_p_read739_phi_phi_fu_886_p4 = ap_phi_reg_pp0_iter1_p_read739_phi_reg_882;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read840_phi_phi_fu_898_p4 = p_read840_phi_reg_894;
    end else begin
        ap_phi_mux_p_read840_phi_phi_fu_898_p4 = ap_phi_reg_pp0_iter1_p_read840_phi_reg_894;
    end
end

always @ (*) begin
    if ((do_init_reg_321 == 1'd0)) begin
        ap_phi_mux_p_read941_phi_phi_fu_910_p4 = p_read941_phi_reg_906;
    end else begin
        ap_phi_mux_p_read941_phi_phi_fu_910_p4 = ap_phi_reg_pp0_iter1_p_read941_phi_reg_906;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_w_index6_phi_fu_339_p6 = w_index_reg_1487;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1492 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_w_index6_phi_fu_339_p6 = 5'd0;
    end else begin
        ap_phi_mux_w_index6_phi_fu_339_p6 = w_index6_reg_336;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1492_pp0_iter2_reg == 1'd1))) begin
        ap_return = trunc_ln46_fu_1314_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w8_ce0 = 1'b1;
    end else begin
        w8_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_fu_1308_p2 = ($signed(sext_ln58_fu_1305_p1) + $signed(ap_phi_mux_empty_phi_fu_1186_p6));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_310 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_331 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_p_read1042_phi_reg_918 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1143_phi_reg_930 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1244_phi_reg_942 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read133_phi_reg_810 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1345_phi_reg_954 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1446_phi_reg_966 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1547_phi_reg_978 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1648_phi_reg_990 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1749_phi_reg_1002 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1850_phi_reg_1014 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1951_phi_reg_1026 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2052_phi_reg_1038 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2153_phi_reg_1050 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2254_phi_reg_1062 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read234_phi_reg_822 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2355_phi_reg_1074 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2456_phi_reg_1086 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2557_phi_reg_1098 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2658_phi_reg_1110 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2759_phi_reg_1122 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2860_phi_reg_1134 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2961_phi_reg_1146 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3062_phi_reg_1158 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3163_phi_reg_1170 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read32_phi_reg_798 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read335_phi_reg_834 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read436_phi_reg_846 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read537_phi_reg_858 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read638_phi_reg_870 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read739_phi_reg_882 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read840_phi_reg_894 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read941_phi_reg_906 = 'bx;

assign icmp_ln46_fu_1207_p2 = ((ap_phi_mux_w_index6_phi_fu_339_p6 == 5'd31) ? 1'b1 : 1'b0);

assign mul_ln73_fu_1289_p1 = mul_ln73_fu_1289_p10;

assign mul_ln73_fu_1289_p10 = a_reg_1496;

assign sext_ln58_fu_1305_p1 = $signed(trunc_ln4_reg_1506);

assign trunc_ln46_fu_1314_p1 = add_ln58_fu_1308_p2[11:0];

assign w8_address0 = zext_ln46_fu_1196_p1;

assign w_index_fu_1201_p2 = (ap_phi_mux_w_index6_phi_fu_339_p6 + 5'd1);

assign zext_ln46_fu_1196_p1 = ap_phi_mux_w_index6_phi_fu_339_p6;

endmodule //myproject_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_16_10_5_3_0_config8_s
